core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('list/<list_id>', views.display_list, name='display_list'),
    path('register', views.register, name='register'),
    path('username_change', views.username_change, name='username_change'),
    path('delete_user', views.delete_user, name='delete_user'),
    path('add_list', views.add_list, name='add_list'),
    path('modify_list/<list_id>', views.modify_list, name='modify_list'),
    path('delete_list/<list_id>', views.delete_list, name='delete_list'),
    path('add_list_item/<list_id>', views.add_list_item, name='add_list_item'),
    path('done/<list_item_id>', views.mark_list_item_done, name='done'),
    path('undo/<list_item_id>', views.mark_list_item_undone, name='undo'),
    path('modify_list_item/<list_item_id>', views.modify_list_item, name='modify_list_item'),
    path('delete_list_item/<list_item_id>', views.delete_list_item, name='delete_list_item')

]

toodoo/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/', PasswordChangeView.as_view(success_url='/'), name='password_change'),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class List(models.Model):
    text = models.CharField(max_length=1000)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


class ListItem(models.Model):
    text = models.CharField(max_length=1000)
    completed = models.BooleanField(default=False)
    list = models.ForeignKey(List, on_delete=models.CASCADE)

core/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import List
from .models import ListItem


class CustomUserChangeForm(ModelForm):
    class Meta:
        model = User
        fields = ['username']


class ListForm(ModelForm):
    class Meta:
        model = List
        fields = ['text']


class ListItemForm(ModelForm):
    class Meta:
        model = ListItem
        fields = ['text']

core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import List
from .models import ListItem
from .models import User
from . import forms


def home(request):
    if request.user.is_authenticated:
        return redirect('list/0')
    else:
        return render(request, 'core/home.html')


def register(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            todo_list = List()
            user = User.objects.get(username=request.POST['username'])
            todo_list.owner = user
            todo_list.text = 'Personal'
            todo_list.save()
            messages.success(request, 'User created')
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'core/register.html', {'form': form})


@login_required
def username_change(request):
    if request.method == 'POST':
        form = forms.CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'User updated')
            return redirect('home')
    else:
        form = forms.CustomUserChangeForm(instance=request.user)
    return render(request, 'core/username_change.html', {'form': form})


@login_required
def delete_user(request):
    user = request.user
    user.is_active = False
    user.save()
    messages.success(request, 'User deleted')
    return redirect('home')


@login_required
def add_list(request):
    if request.method == 'POST':
        todo_list = List()
        todo_list.owner = request.user
        todo_list.text = request.POST['text']
        todo_list.save()
        messages.success(request, 'List added')
    return redirect('display_list', todo_list.id)


@login_required
def modify_list(request, list_id):
    if request.method == 'POST':
        list = List.objects.get(id=list_id)
        if list.owner == request.user:
            list.text = request.POST['text']
            list.save()
            messages.success(request, 'List modified')
        else:
            messages.success(request, 'You are not allowed to modify someone else\'s List', 'danger')
    return redirect('display_list', list_id)


@login_required
def delete_list(request, list_id):
    if request.method == 'POST':
        tbd_list = List.objects.get(id=list_id)
        lists = List.objects.filter(owner=User.objects.get(username=request.user))
        if lists.count() == 1:
            messages.success(request, 'You need to have at least one list', 'danger')
            return redirect('home')
        if tbd_list.owner == request.user:
            tbd_list.delete()
            messages.success(request, 'List deleted')
        else:
            messages.success(request, 'You are not allowed to delete someone else\'s list', 'danger')
    return redirect('home')


@login_required
def add_list_item(request, list_id):
    if request.method == 'POST':
        list = List.objects.get(id=list_id)
        if list.owner == request.user:
            list_item = ListItem()
            list_item.list_id = list_id
            list_item.text = request.POST['text']
            list_item.save()
            messages.success(request, 'Task added')
        else:
            messages.success(request, 'You are not allowed to modify someone else\'s List', 'danger')
    return redirect('display_list', list_id)


@login_required
def mark_list_item_done(request, list_item_id):
    if request.method == 'POST':
        list_item = ListItem.objects.get(id=list_item_id)
        list = List.objects.get(id=list_item.list_id)
        if list.owner == request.user:
            list_item.completed = True
            list_item.save()
            messages.success(request, 'Task marked as done')
        else:
            messages.success(request, 'You are not allowed to modify someone else\'s List', 'danger')
    return redirect('display_list', list.id)


@login_required
def mark_list_item_undone(request, list_item_id):
    if request.method == 'POST':
        list_item = ListItem.objects.get(id=list_item_id)
        active_list = List.objects.get(id=list_item.list_id)
        if active_list.owner == request.user:
            list_item.completed = False
            list_item.save()
            messages.success(request, 'Task marked as undone')
        else:
            messages.success(request, 'You are not allowed to modify someone else\'s List', 'danger')
    return redirect('display_list', active_list.id)


@login_required
def modify_list_item(request, list_item_id):
    if request.method == 'POST':
        list_item = ListItem.objects.get(id=list_item_id)
        list = List.objects.get(id=list_item.list_id)
        if list.owner == request.user:
            list_item.text = request.POST['text']
            list_item.save()
            messages.success(request, 'Task modified')
        else:
            messages.success(request, 'You are not allowed to modify someone else\'s List', 'danger')
    return redirect('display_list', list.id)


@login_required
def delete_list_item(request, list_item_id):
    if request.method == 'POST':
        list_item = ListItem.objects.get(id=list_item_id)
        list = List.objects.get(id=list_item.list_id)
        if list.owner == request.user:
            list_item.delete()
            messages.success(request,'List deleted')
        else:
            messages.success(request, 'You are not allowed to modify someone else\'s List', 'danger')
    return redirect('display_list', list.id)


@login_required
def display_list(request, list_id):
    lists = List.objects.filter(owner=User.objects.get(username=request.user))
    list_items = ListItem.objects.all()
    add_list_form = forms.ListForm()
    add_list_item_form = forms.ListItemForm()
    if list_id == '0':
        return redirect('display_list', lists.order_by('-id')[0].id)
    else:
        active_list = int(list_id)
    if List.objects.get(id=list_id).owner != request.user:
        messages.success(request, 'You are not allowed to access someone else\'s to-do list', 'danger')
        return redirect('display_list', lists.order_by('-id')[0].id)
    return render(request, 'core/toodoos.html', {
        'lists': lists,
        'add_list_form': add_list_form,
        'list_items': list_items,
        'add_list_item_form': add_list_item_form,
        'active_list': active_list})

core/templates/core/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">toodoo</h1>
  <p class="lead">Your website to manage To-Do lists from everywhere.</p>
  <hr class="my-4">
  <p>Feel free to sign-up today</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="/register" role="button">Register</a>
  </p>
</div>
{% endblock content %}

core/templates/core/register.html
{% extends "base.html" %}

{% block content %}
{% include "form_snippet.html" with title='Register' button='Register'%}
<small>Already have an account? <a href="{% url 'login' %}">Login</a></small>
{% endblock content %}

core/templates/core/toodoos.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="row">
    <div id="list_table" class="col-md p-fixed" style="width: 300px">
        <div class="list-group">
            {% if lists %}
                {% for list in lists %}
                    <div class="list-group-item list-group-item-action {% if list.id == active_list %}active{% endif %}"><a class="font-weight-bold text-dark" id="{{ list.id }}text" href="{% url 'display_list' list.id %}" style="word-wrap: break-word">{{ list.text }}</a>
                        <form class="form-inline" id="{{ list.id }}" style="display: none" method="POST" action="{% url 'modify_list' list.id %}">
                            <div class="input-group">
                                {% csrf_token %}
                                <input class="form-control" type="text" name="text" maxlength="1000" required="" value="{{ list.text }}" id="id_text">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" style="height: 38px; width: 38px; background: url({% static 'admin/img/../../../static/img/checked.svg' %}); background-repeat: no-repeat; background-position: 4px 4px; background-size: 30px 30px;" type="submit"/>
                                    <form method="POST" action="{% url 'delete_list' list.id %}">
                                        {% csrf_token %}
                                        <button class="btn btn-outline-secondary p-1" style="height: 38px; width: 38px; background: url({% static 'admin/img/../../../static/img/trashcan.svg' %}); background-repeat: no-repeat; background-position: 3px 4px; background-size: 28px 28px"/>
                                    </form>
                                </span>
                            </div>
                        </form>
                        <div class="btn-group float-right" role="group">
                            <button id="{{ list.id }}editbutton" onclick="document.getElementById({{ list.id }}).style.display='inline';
            document.getElementById('{{ list.id }}text').style.display='none';document.getElementById('{{ list.id }}editbutton').style.display='none';document.getElementById('{{ list.id }}deletebutton').style.display='none';" class="btn btn-outline-secondary p-1" style="height: 38px; width: 38px; background: url({% static 'admin/img/../../../static/img/pencil.svg' %}); background-repeat: no-repeat; background-position: 3px 4px; background-size: 28px 28px"/>
                            <form method="POST" action="{% url 'delete_list' list.id %}">
                                {% csrf_token %}
                                <button id="{{ list.id }}deletebutton" class="btn btn-outline-secondary p-1" style="height: 38px; width: 38px; background: url({% static 'admin/img/../../../static/img/trashcan.svg' %}); background-repeat: no-repeat; background-position: 3px 4px; background-size: 28px 28px"/>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

          <div class="list-group-item form-inline">
              <form method="POST" class="input-group" action="{% url 'add_list' %}">
                  {% csrf_token %}
                  <input class="form-control" placeholder="Add new List" type="text" name="text" maxlength="1000" required="" id="id_text">
                  <span class="input-group-btn">
                      <button class="btn btn-primary p-1" style="height: 38px; width: 38px; background: url({% static 'admin/img/../../../static/img/checked.svg' %}); background-repeat: no-repeat; background-position: 4px 4px; background-size: 30px 30px" type="submit"/>
                  </span>
              </form>
          </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="m-3">
        <div class="row">
            <form class="input-group" method="POST" action="{% url 'add_list_item' active_list %}">
                {% csrf_token %}
                <input class="form-control" type="text" name="text" maxlength="1000" required="" placeholder="Add new task" id="id_text">
                <span class="input-group-btn">
                    <button class="btn btn-primary" style="height: 38px; width: 38px; background: url({% static 'admin/img/../../../static/img/checked.svg' %}); background-repeat: no-repeat; background-position: 4px 4px; background-size: 30px 30px;" type="submit"/>
                </span>
            </form>
        </div>
        <div class="row" style="margin-left: unset; margin-right: -30px">
        {% if list_items %}
            <div class="row w-100">
                <p><h3>To-Do</h3></p>
            </div>
            {% for list_item in list_items %}
                {% if list_item.list_id == active_list and list_item.completed == False %}
                    {% include 'list_item_snippet.html' with button_text='Done' url_name='done' %}
                {% endif %}

            {% endfor %}
            <div class="row w-100">
                <p><h3>Done</h3></p>
            </div>
            {% for list_item in list_items %}
                {% if list_item.list_id == active_list and list_item.completed == True %}
                    {% include 'list_item_snippet.html' with button_text='Undo' url_name='undo' %}
                {% endif %}
            {% endfor %}
        {% endif %}
        </div>
        </div>
    </div>
    </div>
    {% include 'responsive_list.html' %}
{% endblock content %}

core/templates/core/username_change.html
{% extends "base.html" %}

{% block content %}
{% include "form_snippet.html" with title='Change Username' button='Update' %}
{% endblock %}